name: Hello Date and Dir!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
    - name: Current date and directory
      run: |
        echo "Current date: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
        ls -l
    

